sudo: required
dist: trusty

matrix:
  include:
  # - os: linux
  #   env: IS_DOCKER=true
  #   sudo: required
  #   services:
  #     - docker
  #   before_install:
  #     - docker build -t joshuef/beaker ./docker/16
  - os: osx
    env: IS_OSX=true

node_js:
    - '6.3.1'
    
cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache
  
language: node_js


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      
before_script:
  - npm run rebuild
  # - npm run build

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run release:mac; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run release:linux; fi
  # - if [[ $IS_DOCKER ]]; then docker run -v ${TRAVIS_BUILD_DIR}:/build joshuef/beaker /bin/bash -c "cp -R /beaker/dist/* /build"; fi

before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export RELEASE_PKG=$(ls dist/mac/*.dmg); fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export RELEASE_PKG="dist/safer*"; fi
  # - if [[ $IS_DOCKER  ]]; then export RELEASE_PKG="safer*"; fi
  # - if [[ $IS_DOCKER  ]]; then sudo chown safer*; fi
  - echo "deploying ${RELEASE_PKG} to GitHub releases"
  
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Rm1xf0UrI1oPjHQAWrgqEHohh/As8QwDfoK8Ijov+hfAVIsBfl0qhtuaO7/6q1KLgORNHIaXpwVDwoBsWeNscdgfQSbs/ddE3Y+f4LVbMJDU59Q25wvAZNw+ad0/ZuRlhSn/a/hbN+TYmCkZI/+QgmmWFZQGf8ZMTDgY7bU49fCstbtYHeLnWvKpASk/6tmctYLhj92kdcqADvvLLZzaUQrUReoWs9atImuLOJkB4ShKkzpNw2onBsCCCJjjeRaseKUNm0KLP2jZG/kv7ZV8tDJ7DEqLgsI/wc2OBh7h5bR13xOOO6wvYlBoRM7pGy/0KPY15+0DX+Lc9td1Fqm04fr8ZCEehX0kRkbrUUZoHSiEAvnQ/2tm0opAC+6z6tB3ZNGi9qRa5ipqzlQoSUbUYRsTyWwUK0Ca4eeGPETDKkpMFIOxfHPaRK+6qKrNGa0H/Tnoi5kpXIJeIa1ZLLy6tJMqbQWDknwo9AB08QfVbZFk0ws7FR526VOELmhvngk6v0ySjtgxGCFcs6QEWNTa4clswiOZKDOP9vpvMFcrYWBRUt29GBV/Mqa4E+J6CdG2O8nrCiZA+KZ9LNxXFBBW3beo+UxFKwBiJFwzL40zw/hirnzRd5oaNU+o1dZCAUZ1S3xKwOC+wBdPHGF0LgN7EXFHHTwT0UV4sZHNo8pbymk=
  file_glob: true
  file: "${RELEASE_PKG}"
      
  on:
    repo: joshuef/beaker
    branch: release
    tags:   true
    # condition: $IS_DOCKER || $IS_OSX 


notifications:
  email:
    on_success: [change] # default: change
    on_failure: [change] # default: always