platform:
  - x64
  
image: Visual Studio 2015
os: unstable
environment:
  nodejs_version: "6.3.1"

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 6.3.1 x64
  - node --version
  - npm --version
  - npm install npm@next -g
  - npm install
  - npm run rebuild:only
  - npm run build


build_script:
  - node --version
  - npm --version
  - npm run release:windows
# build: off
# test_script:
#   - npm config set msvs_version=2013
#   - npm install --progress false --depth 0
#   - npm test
  